const express = require('express');
const { protect } = require('../middlewares/auth');
const validate = require('../middlewares/validate');
const { generateQuizSchema, submitQuizSchema } = require('../validators/quiz.validator');
const gamificationService = require('../services/gamification.service');
const sendResponse = require('../utils/ResponseWrapper');
const { NotFoundError } = require('../utils/CustomError');
const Quiz = require('../models/quiz.model');
const QuizAttempt = require('../models/quiz-attempt.model');
const aiService = require('../services/ai.service');

const router = express.Router();

router.use(protect);

/**
 * GET /api/v1/quizzes
 * Retrieve casual quizzes with filtering
 */
router.get('/', async (req, res, next) => {
  try {
    const { topic, difficulty } = req.query;
    const query = {};
    if (topic) query.title = new RegExp(topic, 'i');
    if (difficulty) query.difficulty = difficulty;

    const quizzes = await Quiz.find(query).populate('lesson', 'title').lean();
    sendResponse(res, 200, 'Quizzes retrieved successfully', quizzes);
  } catch (error) {
    next(error);
  }
});

/**
 * POST /api/v1/quizzes/generate
 * Generate a casual quiz using AI (Gemini/Groq)
 */
router.post('/generate', validate(generateQuizSchema), async (req, res, next) => {
  try {
    const { topic, questionCount = 5, difficulty = 'intermediate', lessonId, aiProvider } = req.body;
    const quizData = await aiService.generateQuiz(topic, Number(questionCount), difficulty, aiProvider);

    const quiz = await Quiz.create({
      title: `AI Quiz: ${topic}`,
      description: `Practice quiz generated by AI on ${topic}`,
      difficulty,
      lesson: lessonId || null,
      questions: quizData.map(q => ({
        questionText: q.questionText,
        options: q.options,
        correctAnswerIndex: q.correctAnswerIndex,
        points: q.points || 10,
        explanation: q.explanation || '',
      })),
      creator: req.user._id,
    });

    sendResponse(res, 201, 'Quiz generated successfully', quiz);
  } catch (error) {
    next(error);
  }
});

/**
 * GET /api/v1/quizzes/:id
 * Get details of a quiz (hiding answers unless requested for grading check)
 */
router.get('/:id', async (req, res, next) => {
  try {
    const quiz = await Quiz.findById(req.params.id).lean();
    if (!quiz) return next(new NotFoundError('Quiz not found'));

    // Strip out correct answers for student view
    const studentQuiz = {
      ...quiz,
      questions: quiz.questions.map(q => ({
        questionText: q.questionText,
        options: q.options,
        points: q.points,
      })),
    };

    sendResponse(res, 200, 'Quiz retrieved successfully', studentQuiz);
  } catch (error) {
    next(error);
  }
});

/**
 * POST /api/v1/quizzes/:id/submit
 * Submit a quiz attempt and earn gamification XP/coins
 */
router.post('/:id/submit', validate(submitQuizSchema), async (req, res, next) => {
  try {
    const quizId = req.params.id;
    const { answers } = req.body; // Array of selected option indices

    const quiz = await Quiz.findById(quizId);
    if (!quiz) return next(new NotFoundError('Quiz not found'));

    let score = 0;
    const maxScore = quiz.questions.reduce((sum, q) => sum + q.points, 0);
    const results = [];

    quiz.questions.forEach((question, index) => {
      // Find answer matching the index format from schema
      const answerObj = answers.find(a => a.questionIndex === index);
      const userAnswerIndex = answerObj ? answerObj.selectedIndex : null;
      const isCorrect = userAnswerIndex === question.correctAnswerIndex;
      if (isCorrect) score += question.points;

      results.push({
        questionText: question.questionText,
        userAnswerIndex,
        correctAnswerIndex: question.correctAnswerIndex,
        isCorrect,
        explanation: question.explanation,
      });
    });

    const pct = maxScore > 0 ? (score / maxScore) * 100 : 0;
    const passed = pct >= 70;

    const attempt = await QuizAttempt.create({
      quiz: quizId,
      user: req.user._id,
      score,
      maxScore,
      answers: answers.map(a => a.selectedIndex),
      passed,
    });

    // Award XP/coins
    const xpReward = Math.round(score * 1.5);
    const coinsReward = passed ? 10 : 2;
    const rewards = await gamificationService.awardRewards(req.user._id, xpReward, coinsReward);

    // Scan achievements
    const unlockedAchievements = await gamificationService.checkAndUnlockAchievements(req.user._id, {
      quizScore: pct,
    });

    sendResponse(res, 200, 'Quiz completed successfully', {
      attempt,
      score,
      maxScore,
      percentage: pct,
      passed,
      results,
      rewards,
      newlyUnlockedAchievements: unlockedAchievements,
    });
  } catch (error) {
    next(error);
  }
});

module.exports = router;

